NumPy: Numerical Python
Open source library 
It is responsible for numerical operations
It will contain multidimensional array & matrix DS
It provides ndarray , homogeneous n dimensional array
Array ={‘a’,10,10.5} Hetero data types
Numpy = homogeneous  

Difference b/w Array & Numpy : 
Array  - Hetero data types ->Operation speed will be Slow

Numpy - Homo datatypes -> Operation speed is fast 

Install Numpy : 

Pip 
AnaConda , Jupyter 
Installing Jupyter notebook in VS using pip:
python -m pip install jupyter
Jupyter notebook 

Error - 
PS E:\project> jupyter notebook
jupyter : The term 'jupyter' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ jupyter notebook
+ ~~~~~~~
+ CategoryInfo : ObjectNotFound: (jupyter:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

Sln: 
Python -m notebook

In [1]:
pip install numpy

In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.24.1


Arrays from Lists


Create a numpy array using the Python List Data type 


In [4]:
list=[2,3,4,5,6,7,8]

In [5]:
a=np.array(list)

In [6]:
print(a)

[2 3 4 5 6 7 8]


In [7]:
print(list)

[2, 3, 4, 5, 6, 7, 8]


Arrays from Scratch


Create a numpy array using traditional syntax of ndarray (ndarray is object of numpy )

In [8]:
arr=np.array([1,2,3,4,5])

In [9]:
print(arr)

[1 2 3 4 5]


In [10]:
print(type(arr))

<class 'numpy.ndarray'>


In [11]:
print(type(list))

<class 'list'>


In [12]:
print(type(a))

<class 'numpy.ndarray'>


Understanding the Dimensions of numpy array

In [15]:
a0d=np.array(60) #0 dimension array
a1d=np.array([1,2,3,4,5,6,7])# 1 dimension array
a2d=np.array([[1,2,3,4],[5,6,7,8]]) #2 dimension array
a3d=np.array([[[1,2,3],[1,4,5]],[[4,5,6],[7,8,9]]]) #3 dimension array, addition of 2 , 2 dim array
print(a0d) # 0 dim numpy array
print(a1d) # 1 dim numpy array
print(a2d) # 2 dim numpy array
print(a3d) # 3 dim numpy array

60
[1 2 3 4 5 6 7]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2 3]
  [1 4 5]]

 [[4 5 6]
  [7 8 9]]]


The Basics of NumPy Arrays	
    NumPy Array Attributes
	Array Indexing: Accessing Single Elements
	Array Slicing: Accessing Subarrays
	Reshaping of Arrays
	Array Concatenation
	Splitting

The Basics of NumPy Arrays
=>Numpy array Manipulation (Changing)

 NumPy Array Attributes:
 1.Determining the size 0d,1d,2d,3d
 2.Shape
 3.Memory Consumption
 4.Data types of arrays
 

In [19]:
#x1=np.random.randint(10,size=6)
#x1=np.array([[1,2,3,4],[5,6,7,8]])
x1=np.array([[[1,2,3],[1,4,5]],[[4,5,6],[7,8,9]]])

print(x1.ndim) #Determining the size 
print(x1.shape)#Shape => give the dim, count of value
print(x1.size)#Memory Consumption
print(x1.dtype)#Data types of arrays

3
(2, 2, 3)
12
int32


Array Indexing: Accessing Single Elements
=>Indexing means points a value in array 


In [29]:
a0d=np.array(60) #0 dimension array
a1d=np.array([1,2,3,4,5,6,7])# 1 dimension array
a2d=np.array([[1,2,3,4],[5,6,7,8]]) #2 dimension array
a3d=np.array([[[1,2,3],[1,4,5]],[[4,5,6],[7,8,9]]]) #3 dimension array, addition of 2 , 2 dim array
#Accessing the Data in numpy array
print(a0d) 
print(a1d[2]) #access the value 3
print(a2d[1,0]) #access value 5
print(a3d[1,1,2]) #access value 9


60
3
5
9


Array Slicing: Accessing Subarrays
=>x[start:stop:step]
Default value start=0, stop=size of dimension, step=1

In [37]:
a1d=np.array([1,2,3,4,5,6,7])# 1 dimension array
#Slicing of 1D numpy array
#Getting first few elements 
print(a1d[:4]) #neglect the given index and print all prev value
#Getting elemnt after given index
print(a1d[4:]) # include the given index and print till the end dimension
#Getting middle array
print(a1d[3:5]) #both index given is included
#Skip all 2nd value 
print(a1d[::2])
print(a1d[4::2])
#Reverse option
print(a1d[::-1])


[1 2 3 4]
[5 6 7]
[4 5]
[1 3 5 7]
[5 7]
[7 6 5 4 3 2 1]


Multi dimensional Numpy Array slicing

In [44]:
a2d=np.array([[1,2,3,4],[5,6,7,8]]) #2 dimension array
#slicing
print(a2d)
print(a2d[:2,:3]) #2 rows, 2 columns
print(a2d[:2,::2]) #skipping column
#reverse of multi D
print(a2d[::-1,::-1])

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3]
 [5 6 7]]
[[1 3]
 [5 7]]
[[8 7 6 5]
 [4 3 2 1]]


Reshaping of Arrays
(a2d.shape)=>(dimension , count)

In [51]:
x1=np.array([1,2,3,4,5,6])
print(x1.shape)#Shape => give the dim, count of value
#reshape this 1d to 2d 
print("Before reshaping")
print(x1)
print("After Reshaping")
print(x1.reshape(3,2))

(6,)
Before reshaping
[1 2 3 4 5 6]
After Reshaping
[[1 2]
 [3 4]
 [5 6]]


Array Concatenation:
2 numpy array => add that then concat will be used
syntax:
numpy.concatenate([a1,a2])

In [52]:
a1=np.array([1,2,3,4,5,6])
a2=np.array([7,8,9,10,11,12])
#Concat these 2 numpy array
print(np.concatenate([a1,a2]))


[ 1  2  3  4  5  6  7  8  9 10 11 12]


Splitting:
syntax:
np.split
np.hsplit
np.vsplit

In [68]:
s=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ss=np.split(s,2)
s1=ss[0]
s2=ss[1]
print(s1)
print(s2)


[1 2 3 4 5 6]
[ 7  8  9 10 11 12]


NumPy Universal Functions	
=>It will be responsible for math problems 
=>It contains plenty of operations inside it 
Characteristics:
1.It will work with ndarray
2.Broadcasting
3.It includes all types of functions like ->Arithmetic funs,  Trignometric, Statistical , Bit twiddling fns
    Introducing UFuncs
	Exploring NumPy’s Ufuncs
	Advanced Ufunc Features

Exploring NumPy’s Ufuncs
a.Arithmetic funs:
    It will have add, sub , mul, div
    
    np.add(a,b)
    np.subtract(a,b)
    np.multiply(a,b)
    np.division(a,b)
    np.floor_divide(a,b)
    np.power(a,b)
    np.mod(a,b)
    

In [5]:
import numpy as np
a=[1,2,3,4]
b=[5,6,7,8]
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.floor_divide(a,b))
print(np.power(a,b))
print(np.mod(a,b))

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0 0 0 0]
[    1    64  2187 65536]
[1 2 3 4]


Trignometric fn:
sin
cos
tan
arcsin ->inverse
arccos
arctan
hypot
sinh
cosh
tanh
arcsinh ->inverse
arccosh
arctanh
Conversion of rad to deg & deg to rad:
deg2rad
rad2deg


In [15]:
angles=np.array([0,30,45,60,90,180])
print(angles)
radians=np.deg2rad(angles)
print(radians)

sinval= np.sin(radians)
print(sinval)
print(np.cos(radians))
print(np.tan(radians))
print(np.arcsin(sinval))
print(np.arccos(np.cos(radians)))
print(np.arctan(np.tan(radians)))
print(np.hypot(4,3)) # hypot of right base =4, height =3
print(np.sinh(radians))
print(np.tanh(radians))
print(np.cosh(radians))
print(np.arcsinh(np.sinh(radians)))
print(np.arccosh(np.cosh(radians)))
print(np.arctanh(np.tanh(radians)))

[  0  30  45  60  90 180]
[0.         0.52359878 0.78539816 1.04719755 1.57079633 3.14159265]
[0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 1.22464680e-16]
[ 1.00000000e+00  8.66025404e-01  7.07106781e-01  5.00000000e-01
  6.12323400e-17 -1.00000000e+00]
[ 0.00000000e+00  5.77350269e-01  1.00000000e+00  1.73205081e+00
  1.63312394e+16 -1.22464680e-16]
[0.00000000e+00 5.23598776e-01 7.85398163e-01 1.04719755e+00
 1.57079633e+00 1.22464680e-16]
[0.         0.52359878 0.78539816 1.04719755 1.57079633 3.14159265]
[ 0.00000000e+00  5.23598776e-01  7.85398163e-01  1.04719755e+00
  1.57079633e+00 -1.22464680e-16]
5.0
[ 0.          0.54785347  0.86867096  1.24936705  2.3012989  11.54873936]
[0.         0.48047278 0.6557942  0.78071444 0.91715234 0.99627208]
[ 1.          1.14023832  1.32460909  1.60028686  2.50917848 11.59195328]
[0.         0.52359878 0.78539816 1.04719755 1.57079633 3.14159265]
[0.         0.52359878 0.78539816 1.04719755 1.57079633 3.14159265]

Statistical Funs:
mean
median
std
var
average
min and max

In [16]:
a=np.array([2,5,6,7,8,9])
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.average(a))
print(np.amin(a),np.amax(a))

6.166666666666667
6.5
2.266911751455907
5.138888888888889
6.166666666666667
2 9


Bit - Twiddling Fns:
bitwise_and
bitwise_or
bitwise_xor
invert
left_shift
right_shift

In [17]:
a=np.array([1,2,3,4,5,6,7])
b=np.array([8,9,10,11,12,13,14])
print(np.bitwise_and(a,b))
print(np.bitwise_or(a,b))
print(np.bitwise_xor(a,b))
print(np.invert(a))
print(np.left_shift(a,1))
print(np.right_shift(a,1))

[0 0 2 0 4 4 6]
[ 9 11 11 15 13 15 15]
[ 9 11  9 15  9 11  9]
[-2 -3 -4 -5 -6 -7 -8]
[ 2  4  6  8 10 12 14]
[0 1 1 2 2 3 3]


Advanced Ufunc Features:
=>It will give the output in the logic function itself 
=>YOu can add logic to the same output in single ufunc

In [31]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.array([5,6,7,8,11,2,4,5,6,7])
z=np.empty(10)
y=np.empty(10)
np.add(a,b, out=z[::-1]) #inverse
np.power(2,a,out=y[::1]) #slicing skip
print(z)
print(y)



[17. 15. 13. 11.  8. 16. 12. 10.  8.  6.]
[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


Aggregation:
    1.Min
	2.Max
	3.Summing the values in an Array
  =>Working in large data set and perform operations like add, div, mean ,median, max, min is easier while u use the in-built aggregation fns
  

In [38]:
#a=np.array([1,2,3,4,5])
a=np.random.rand(100) # rand(100000000)
print(a)
maxval=max(a)
minval=min(a)
print(maxval,minval)
print(a.sum())

[0.89184095 0.08302551 0.35585572 0.28417676 0.76842334 0.9377665
 0.21755711 0.72790947 0.16748304 0.46416696 0.7578623  0.13727782
 0.65005519 0.00263532 0.40059594 0.05206243 0.41634094 0.57263585
 0.88116582 0.36177287 0.9723229  0.00751084 0.96447055 0.35538655
 0.56336979 0.23476372 0.05444941 0.01381917 0.62202428 0.07251111
 0.94467104 0.89958121 0.399481   0.3824755  0.23617994 0.11093563
 0.21579727 0.17575812 0.07160565 0.94524371 0.68711981 0.12398279
 0.14453353 0.25408947 0.88747107 0.01702397 0.03171162 0.5750205
 0.02048982 0.25554125 0.66939188 0.63440698 0.70783612 0.93927537
 0.3344814  0.07261716 0.06557881 0.07869472 0.47829822 0.70878156
 0.02743886 0.04956426 0.98766756 0.494099   0.4084318  0.61583911
 0.85719589 0.49542024 0.43461819 0.39698802 0.9127716  0.74079079
 0.65961871 0.53774115 0.46300839 0.75139287 0.80754669 0.25286238
 0.07781909 0.83011781 0.65200512 0.40077672 0.98638342 0.55310354
 0.92724105 0.96995801 0.52634103 0.38582789 0.0340177  0.227278