Random : Computer will gen the random value , Numpy 


In [8]:
import numpy as np
import pandas as pd
a=np.array([1,2,3,4,5])
print(a)
b=np.random.rand(3,2) #3 dim with 2 size
print(b)
c=np.random.randint(10,size=(4,3)) # setting the limit value to generate the random value
print(c)
rd=np.random.RandomState(42) 
d=pd.DataFrame(rd.randint(0,10,(4,3)))
print(d)

[1 2 3 4 5]
[[0.49970446 0.94699186]
 [0.10546369 0.94029989]
 [0.38140552 0.02526051]]
[[0 3 3]
 [9 3 7]
 [8 5 0]
 [6 2 4]]
   0  1  2
0  6  3  7
1  4  6  9
2  2  6  7
3  4  3  7
